# Generated by Django 3.0.8 on 2020-07-03 18:51

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='add_date',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='add_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 7, 3, 18, 51, 26, 581104, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
